#include "ex2/struct1.h"
#include "ex2/struct2.h"
#include "ex2/struct3.h"
#include "ex2/struct4.h"
#include "ex2/struct5.h"
#include "ex2/struct_arr1.h"
#include "ex2/struct_arr2.h"
#include "ex2/nested_struct2.h"
