#include "../ex6/assertion1.h"
#include "../ex6/math1.h"
#include "../ex6/math2.h"
#include "../ex6/check_input.h"
#include "../ex6/my_itoa.h"
#include "../ex6/random1.h"
#include "../ex6/random2.h"
#include "../ex6/random3.h"
#include "../ex6/qsort.h"
#include "../ex6/bsearch.h"
#include "../ex6/setjmp.h"
#include "../ex6/simple_shell.h"
#include "../ex6/raise_signal.h"
#include "../ex6/memchr.h"
#include "../ex6/memcmp.h"

